<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateUserKotaTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */

    private static $kota = [
            ['id_provinsi'=>33, 'nama'=>'Kabupaten Aceh Barat                        '],
            ['id_provinsi'=>33, 'nama'=>'Kabupaten Aceh Barat Daya                   '],
            ['id_provinsi'=>33, 'nama'=>'Kabupaten Aceh Besar                        '],
            ['id_provinsi'=>33, 'nama'=>'Kabupaten Aceh Jaya                         '],
            ['id_provinsi'=>33, 'nama'=>'Kabupaten Aceh Selatan                      '],
            ['id_provinsi'=>33, 'nama'=>'Kabupaten Aceh Singkil                      '],
            ['id_provinsi'=>33, 'nama'=>'Kabupaten Aceh Tamiang                      '],
            ['id_provinsi'=>33, 'nama'=>'Kabupaten Aceh Tengah                       '],
            ['id_provinsi'=>33, 'nama'=>'Kabupaten Aceh Tenggara                     '],
            ['id_provinsi'=>33, 'nama'=>'Kabupaten Aceh Timur                        '],
            ['id_provinsi'=>33, 'nama'=>'Kabupaten Aceh Utara                        '],
            ['id_provinsi'=>33, 'nama'=>'Kabupaten Bener Meriah                      '],
            ['id_provinsi'=>33, 'nama'=>'Kabupaten Bireuen                           '],
            ['id_provinsi'=>33, 'nama'=>'Kabupaten Gayo Lues                         '],
            ['id_provinsi'=>33, 'nama'=>'Kabupaten Nagan Raya                        '],
            ['id_provinsi'=>33, 'nama'=>'Kabupaten Pidie                             '],
            ['id_provinsi'=>33, 'nama'=>'Kabupaten Pidie Jaya                        '],
            ['id_provinsi'=>33, 'nama'=>'Kabupaten Simeulue                          '],
            ['id_provinsi'=>33, 'nama'=>'Kota Banda Aceh                             '],
            ['id_provinsi'=>33, 'nama'=>'Kota Langsa                                 '],
            ['id_provinsi'=>33, 'nama'=>'Kota Lhokseumawe                            '],
            ['id_provinsi'=>33, 'nama'=>'Kota Sabang                                 '],
            ['id_provinsi'=>33, 'nama'=>'Kota Subulussalam                           '],
            ['id_provinsi'=>28, 'nama'=>'Kabupaten Asahan                            '],
            ['id_provinsi'=>28, 'nama'=>'Kabupaten Batubara                          '],
            ['id_provinsi'=>28, 'nama'=>'Kabupaten Dairi                             '],
            ['id_provinsi'=>28, 'nama'=>'Kabupaten Deli Serdang                      '],
            ['id_provinsi'=>28, 'nama'=>'Kabupaten Humbang Hasundutan                '],
            ['id_provinsi'=>28, 'nama'=>'Kabupaten Karo                              '],
            ['id_provinsi'=>28, 'nama'=>'Kabupaten Labuhanbatu                       '],
            ['id_provinsi'=>28, 'nama'=>'Kabupaten Labuhanbatu Selatan               '],
            ['id_provinsi'=>28, 'nama'=>'Kabupaten Labuhanbatu Utara                 '],
            ['id_provinsi'=>28, 'nama'=>'Kabupaten Langkat                           '],
            ['id_provinsi'=>28, 'nama'=>'Kabupaten Mandailing Natal                  '],
            ['id_provinsi'=>28, 'nama'=>'Kabupaten Nias                              '],
            ['id_provinsi'=>28, 'nama'=>'Kabupaten Nias Barat                        '],
            ['id_provinsi'=>28, 'nama'=>'Kabupaten Nias Selatan                      '],
            ['id_provinsi'=>28, 'nama'=>'Kabupaten Nias Utara                        '],
            ['id_provinsi'=>28, 'nama'=>'Kabupaten Padang Lawas                      '],
            ['id_provinsi'=>28, 'nama'=>'Kabupaten Padang Lawas Utara                '],
            ['id_provinsi'=>28, 'nama'=>'Kabupaten Pakpak Bharat                     '],
            ['id_provinsi'=>28, 'nama'=>'Kabupaten Samosir                           '],
            ['id_provinsi'=>28, 'nama'=>'Kabupaten Serdang Bedagai                   '],
            ['id_provinsi'=>28, 'nama'=>'Kabupaten Simalungun                        '],
            ['id_provinsi'=>28, 'nama'=>'Kabupaten Tapanuli Selatan                  '],
            ['id_provinsi'=>28, 'nama'=>'Kabupaten Tapanuli Tengah                   '],
            ['id_provinsi'=>28, 'nama'=>'Kabupaten Tapanuli Utara                    '],
            ['id_provinsi'=>28, 'nama'=>'Kabupaten Toba Samosir                      '],
            ['id_provinsi'=>28, 'nama'=>'Kota Binjai                                 '],
            ['id_provinsi'=>28, 'nama'=>'Kota Gunungsitoli                           '],
            ['id_provinsi'=>28, 'nama'=>'Kota Medan                                  '],
            ['id_provinsi'=>28, 'nama'=>'Kota Padangsidempuan                        '],
            ['id_provinsi'=>28, 'nama'=>'Kota Pematangsiantar                        '],
            ['id_provinsi'=>28, 'nama'=>'Kota Sibolga                                '],
            ['id_provinsi'=>28, 'nama'=>'Kota Tanjungbalai                           '],
            ['id_provinsi'=>28, 'nama'=>'Kota Tebing Tinggi                          '],
            ['id_provinsi'=>6, 'nama'=>'Kabupaten Bengkulu Selatan                  '],
            ['id_provinsi'=>6, 'nama'=>'Kabupaten Bengkulu Tengah                   '],
            ['id_provinsi'=>6, 'nama'=>'Kabupaten Bengkulu Utara                    '],
            ['id_provinsi'=>6, 'nama'=>'Kabupaten Kaur                              '],
            ['id_provinsi'=>6, 'nama'=>'Kabupaten Kepahiang                         '],
            ['id_provinsi'=>6, 'nama'=>'Kabupaten Lebong                            '],
            ['id_provinsi'=>6, 'nama'=>'Kabupaten Mukomuko                          '],
            ['id_provinsi'=>6, 'nama'=>'Kabupaten Rejang Lebong                     '],
            ['id_provinsi'=>6, 'nama'=>'Kabupaten Seluma                            '],
            ['id_provinsi'=>6, 'nama'=>'Kota Bengkulu                               '],
            ['id_provinsi'=>8, 'nama'=>'Kabupaten Batanghari                        '],
            ['id_provinsi'=>8, 'nama'=>'Kabupaten Bungo                             '],
            ['id_provinsi'=>8, 'nama'=>'Kabupaten Kerinci                           '],
            ['id_provinsi'=>8, 'nama'=>'Kabupaten Merangin                          '],
            ['id_provinsi'=>8, 'nama'=>'Kabupaten Muaro Jambi                       '],
            ['id_provinsi'=>8, 'nama'=>'Kabupaten Sarolangun                        '],
            ['id_provinsi'=>8, 'nama'=>'Kabupaten Tanjung Jabung Barat              '],
            ['id_provinsi'=>8, 'nama'=>'Kabupaten Tanjung Jabung Timur              '],
            ['id_provinsi'=>8, 'nama'=>'Kabupaten Tebo                              '],
            ['id_provinsi'=>8, 'nama'=>'Kota Jambi                                  '],
            ['id_provinsi'=>8, 'nama'=>'Kota Sungai Penuh                           '],
            ['id_provinsi'=>23, 'nama'=>'Kabupaten Bengkalis                         '],
            ['id_provinsi'=>23, 'nama'=>'Kabupaten Indragiri Hilir                   '],
            ['id_provinsi'=>23, 'nama'=>'Kabupaten Indragiri Hulu                    '],
            ['id_provinsi'=>23, 'nama'=>'Kabupaten Kampar                            '],
            ['id_provinsi'=>23, 'nama'=>'Kabupaten Kuantan Singingi                  '],
            ['id_provinsi'=>23, 'nama'=>'Kabupaten Pelalawan                         '],
            ['id_provinsi'=>23, 'nama'=>'Kabupaten Rokan Hilir                       '],
            ['id_provinsi'=>23, 'nama'=>'Kabupaten Rokan Hulu                        '],
            ['id_provinsi'=>23, 'nama'=>'Kabupaten Siak                              '],
            ['id_provinsi'=>23, 'nama'=>'Kabupaten Kepulauan Meranti                 '],
            ['id_provinsi'=>23, 'nama'=>'Kota Dumai                                  '],
            ['id_provinsi'=>23, 'nama'=>'Kota Pekanbaru                              '],
            ['id_provinsi'=>28, 'nama'=>'Kabupaten Agam                              '],
            ['id_provinsi'=>28, 'nama'=>'Kabupaten Dharmasraya                       '],
            ['id_provinsi'=>28, 'nama'=>'Kabupaten Kepulauan Mentawai                '],
            ['id_provinsi'=>28, 'nama'=>'Kabupaten Lima Puluh Kota                   '],
            ['id_provinsi'=>28, 'nama'=>'Kabupaten Padang Pariaman                   '],
            ['id_provinsi'=>28, 'nama'=>'Kabupaten Pasaman                           '],
            ['id_provinsi'=>28, 'nama'=>'Kabupaten Pasaman Barat                     '],
            ['id_provinsi'=>28, 'nama'=>'Kabupaten Pesisir Selatan                   '],
            ['id_provinsi'=>28, 'nama'=>'Kabupaten Sijunjung                         '],
            ['id_provinsi'=>28, 'nama'=>'Kabupaten Solok                             '],
            ['id_provinsi'=>28, 'nama'=>'Kabupaten Solok Selatan                     '],
            ['id_provinsi'=>28, 'nama'=>'Kabupaten Tanah Datar                       '],
            ['id_provinsi'=>28, 'nama'=>'Kota Bukittinggi                            '],
            ['id_provinsi'=>28, 'nama'=>'Kota Padang                                 '],
            ['id_provinsi'=>28, 'nama'=>'Kota Padangpanjang                          '],
            ['id_provinsi'=>28, 'nama'=>'Kota Pariaman                               '],
            ['id_provinsi'=>28, 'nama'=>'Kota Payakumbuh                             '],
            ['id_provinsi'=>28, 'nama'=>'Kota Sawahlunto                             '],
            ['id_provinsi'=>28, 'nama'=>'Kota Solok                                  '],
            ['id_provinsi'=>29, 'nama'=>'Kabupaten Banyuasin                         '],
            ['id_provinsi'=>29, 'nama'=>'Kabupaten Empat Lawang                      '],
            ['id_provinsi'=>29, 'nama'=>'Kabupaten Lahat                             '],
            ['id_provinsi'=>29, 'nama'=>'Kabupaten Muara Enim                        '],
            ['id_provinsi'=>29, 'nama'=>'Kabupaten Musi Banyuasin                    '],
            ['id_provinsi'=>29, 'nama'=>'Kabupaten Musi Rawas                        '],
            ['id_provinsi'=>29, 'nama'=>'Kabupaten Ogan Ilir                         '],
            ['id_provinsi'=>29, 'nama'=>'Kabupaten Ogan Komering Ilir                '],
            ['id_provinsi'=>29, 'nama'=>'Kabupaten Ogan Komering Ulu                 '],
            ['id_provinsi'=>29, 'nama'=>'Kabupaten Ogan Komering Ulu Selatan         '],
            ['id_provinsi'=>29, 'nama'=>'Kabupaten Ogan Komering Ulu Timur           '],
            ['id_provinsi'=>29, 'nama'=>'Kota Lubuklinggau                           '],
            ['id_provinsi'=>29, 'nama'=>'Kota Pagar Alam                             '],
            ['id_provinsi'=>29, 'nama'=>'Kota Palembang                              '],
            ['id_provinsi'=>29, 'nama'=>'Kota Prabumulih                             '],
            ['id_provinsi'=>16, 'nama'=>'Kabupaten Lampung Barat                     '],
            ['id_provinsi'=>16, 'nama'=>'Kabupaten Lampung Selatan                   '],
            ['id_provinsi'=>16, 'nama'=>'Kabupaten Lampung Tengah                    '],
            ['id_provinsi'=>16, 'nama'=>'Kabupaten Lampung Timur                     '],
            ['id_provinsi'=>16, 'nama'=>'Kabupaten Lampung Utara                     '],
            ['id_provinsi'=>16, 'nama'=>'Kabupaten Mesuji                            '],
            ['id_provinsi'=>16, 'nama'=>'Kabupaten Pesawaran                         '],
            ['id_provinsi'=>16, 'nama'=>'Kabupaten Pringsewu                         '],
            ['id_provinsi'=>16, 'nama'=>'Kabupaten Tanggamus                         '],
            ['id_provinsi'=>16, 'nama'=>'Kabupaten Tulang Bawang                     '],
            ['id_provinsi'=>16, 'nama'=>'Kabupaten Tulang Bawang Barat               '],
            ['id_provinsi'=>16, 'nama'=>'Kabupaten Way Kanan                         '],
            ['id_provinsi'=>16, 'nama'=>'Kota Bandar Lampung                         '],
            ['id_provinsi'=>16, 'nama'=>'Kota Metro                                  '],
            ['id_provinsi'=>5, 'nama'=>'Kabupaten Bangka                            '],
            ['id_provinsi'=>5, 'nama'=>'Kabupaten Bangka Barat                      '],
            ['id_provinsi'=>5, 'nama'=>'Kabupaten Bangka Selatan                    '],
            ['id_provinsi'=>5, 'nama'=>'Kabupaten Bangka Tengah                     '],
            ['id_provinsi'=>5, 'nama'=>'Kabupaten Belitung                          '],
            ['id_provinsi'=>5, 'nama'=>'Kabupaten Belitung Timur                    '],
            ['id_provinsi'=>5, 'nama'=>'Kota Pangkal Pinang                         '],
            ['id_provinsi'=>15, 'nama'=>'Kabupaten Bintan                            '],
            ['id_provinsi'=>15, 'nama'=>'Kabupaten Karimun                           '],
            ['id_provinsi'=>15, 'nama'=>'Kabupaten Kepulauan Anambas                 '],
            ['id_provinsi'=>15, 'nama'=>'Kabupaten Lingga                            '],
            ['id_provinsi'=>15, 'nama'=>'Kabupaten Natuna                            '],
            ['id_provinsi'=>15, 'nama'=>'Kota Batam                                  '],
            ['id_provinsi'=>15, 'nama'=>'Kota Tanjung Pinang                         '],
            ['id_provinsi'=>3, 'nama'=>'Kabupaten Tangerang                         '],
            ['id_provinsi'=>3, 'nama'=>'Kabupaten Serang                            '],
            ['id_provinsi'=>3, 'nama'=>'Kabupaten Lebak                             '],
            ['id_provinsi'=>3, 'nama'=>'Kabupaten Pandeglang                        '],
            ['id_provinsi'=>3, 'nama'=>'Kota Tangerang                              '],
            ['id_provinsi'=>3, 'nama'=>'Kota Serang                                 '],
            ['id_provinsi'=>3, 'nama'=>'Kota Cilegon                                '],
            ['id_provinsi'=>3, 'nama'=>'Kota Tangerang Selatan                      '],
            ['id_provinsi'=>2, 'nama'=>'Kabupaten Bandung                           '],
            ['id_provinsi'=>2, 'nama'=>'Kabupaten Bandung Barat                     '],
            ['id_provinsi'=>2, 'nama'=>'Kabupaten Bekasi                            '],
            ['id_provinsi'=>2, 'nama'=>'Kabupaten Bogor                             '],
            ['id_provinsi'=>2, 'nama'=>'Kabupaten Ciamis                            '],
            ['id_provinsi'=>2, 'nama'=>'Kabupaten Cianjur                           '],
            ['id_provinsi'=>2, 'nama'=>'Kabupaten Cirebon                           '],
            ['id_provinsi'=>2, 'nama'=>'Kabupaten Garut                             '],
            ['id_provinsi'=>2, 'nama'=>'Kabupaten Indramayu                         '],
            ['id_provinsi'=>2, 'nama'=>'Kabupaten Karawang                          '],
            ['id_provinsi'=>2, 'nama'=>'Kabupaten Kuningan                          '],
            ['id_provinsi'=>2, 'nama'=>'Kabupaten Majalengka                        '],
            ['id_provinsi'=>2, 'nama'=>'Kabupaten Purwakarta                        '],
            ['id_provinsi'=>2, 'nama'=>'Kabupaten Subang                            '],
            ['id_provinsi'=>2, 'nama'=>'Kabupaten Sukabumi                          '],
            ['id_provinsi'=>2, 'nama'=>'Kabupaten Sumedang                          '],
            ['id_provinsi'=>2, 'nama'=>'Kabupaten Tasikmalaya                       '],
            ['id_provinsi'=>2, 'nama'=>'Kota Bandung                                '],
            ['id_provinsi'=>2, 'nama'=>'Kota Banjar                                 '],
            ['id_provinsi'=>2, 'nama'=>'Kota Bekasi                                 '],
            ['id_provinsi'=>2, 'nama'=>'Kota Bogor                                  '],
            ['id_provinsi'=>2, 'nama'=>'Kota Cimahi                                 '],
            ['id_provinsi'=>2, 'nama'=>'Kota Cirebon                                '],
            ['id_provinsi'=>2, 'nama'=>'Kota Depok                                  '],
            ['id_provinsi'=>2, 'nama'=>'Kota Sukabumi                               '],
            ['id_provinsi'=>2, 'nama'=>'Kota Tasikmalaya                            '],
            ['id_provinsi'=>1, 'nama'=>'Kepulauan Seribu                            '],
            ['id_provinsi'=>1, 'nama'=>'Jakarta Barat                               '],
            ['id_provinsi'=>1, 'nama'=>'Jakarta Pusat                               '],
            ['id_provinsi'=>1, 'nama'=>'Jakarta Selatan                             '],
            ['id_provinsi'=>1, 'nama'=>'Jakarta Timur                               '],
            ['id_provinsi'=>1, 'nama'=>'Jakarta Utara                               '],
            ['id_provinsi'=>9, 'nama'=>'Kabupaten Banjarnegara                      '],
            ['id_provinsi'=>9, 'nama'=>'Kabupaten Banyumas                          '],
            ['id_provinsi'=>9, 'nama'=>'Kabupaten Batang                            '],
            ['id_provinsi'=>9, 'nama'=>'Kabupaten Blora                             '],
            ['id_provinsi'=>9, 'nama'=>'Kabupaten Boyolali                          '],
            ['id_provinsi'=>9, 'nama'=>'Kabupaten Brebes                            '],
            ['id_provinsi'=>9, 'nama'=>'Kabupaten Cilacap                           '],
            ['id_provinsi'=>9, 'nama'=>'Kabupaten Demak                             '],
            ['id_provinsi'=>9, 'nama'=>'Kabupaten Grobogan                          '],
            ['id_provinsi'=>9, 'nama'=>'Kabupaten Jepara                            '],
            ['id_provinsi'=>9, 'nama'=>'Kabupaten Karanganyar                       '],
            ['id_provinsi'=>9, 'nama'=>'Kabupaten Kebumen                           '],
            ['id_provinsi'=>9, 'nama'=>'Kabupaten Kendal                            '],
            ['id_provinsi'=>9, 'nama'=>'Kabupaten Klaten                            '],
            ['id_provinsi'=>9, 'nama'=>'Kabupaten Kudus                             '],
            ['id_provinsi'=>9, 'nama'=>'Kabupaten Magelang                          '],
            ['id_provinsi'=>9, 'nama'=>'Kabupaten Pati                              '],
            ['id_provinsi'=>9, 'nama'=>'Kabupaten Pekalongan                        '],
            ['id_provinsi'=>9, 'nama'=>'Kabupaten Pemalang                          '],
            ['id_provinsi'=>9, 'nama'=>'Kabupaten Purbalingga                       '],
            ['id_provinsi'=>9, 'nama'=>'Kabupaten Purworejo                         '],
            ['id_provinsi'=>9, 'nama'=>'Kabupaten Rembang                           '],
            ['id_provinsi'=>9, 'nama'=>'Kabupaten Semarang                          '],
            ['id_provinsi'=>9, 'nama'=>'Kabupaten Sragen                            '],
            ['id_provinsi'=>9, 'nama'=>'Kabupaten Sukoharjo                         '],
            ['id_provinsi'=>9, 'nama'=>'Kabupaten Tegal                             '],
            ['id_provinsi'=>9, 'nama'=>'Kabupaten Temanggung                        '],
            ['id_provinsi'=>9, 'nama'=>'Kabupaten Wonogiri                          '],
            ['id_provinsi'=>9, 'nama'=>'Kabupaten Wonosobo                          '],
            ['id_provinsi'=>9, 'nama'=>'Kota Magelang                               '],
            ['id_provinsi'=>9, 'nama'=>'Kota Pekalongan                             '],
            ['id_provinsi'=>9, 'nama'=>'Kota Salatiga                               '],
            ['id_provinsi'=>9, 'nama'=>'Kota Semarang                               '],
            ['id_provinsi'=>9, 'nama'=>'Kota Surakarta                              '],
            ['id_provinsi'=>9, 'nama'=>'Kota Tegal                                  '],
            ['id_provinsi'=>10, 'nama'=>'Kabupaten Bangkalan                         '],
            ['id_provinsi'=>10, 'nama'=>'Kabupaten Banyuwangi                        '],
            ['id_provinsi'=>10, 'nama'=>'Kabupaten Blitar                            '],
            ['id_provinsi'=>10, 'nama'=>'Kabupaten Bojonegoro                        '],
            ['id_provinsi'=>10, 'nama'=>'Kabupaten Bondowoso                         '],
            ['id_provinsi'=>10, 'nama'=>'Kabupaten Gresik                            '],
            ['id_provinsi'=>10, 'nama'=>'Kabupaten Jember                            '],
            ['id_provinsi'=>10, 'nama'=>'Kabupaten Jombang                           '],
            ['id_provinsi'=>10, 'nama'=>'Kabupaten Kediri                            '],
            ['id_provinsi'=>10, 'nama'=>'Kabupaten Lamongan                          '],
            ['id_provinsi'=>10, 'nama'=>'Kabupaten Lumajang                          '],
            ['id_provinsi'=>10, 'nama'=>'Kabupaten Madiun                            '],
            ['id_provinsi'=>10, 'nama'=>'Kabupaten Magetan                           '],
            ['id_provinsi'=>10, 'nama'=>'Kabupaten Malang                            '],
            ['id_provinsi'=>10, 'nama'=>'Kabupaten Mojokerto                         '],
            ['id_provinsi'=>10, 'nama'=>'Kabupaten Nganjuk                           '],
            ['id_provinsi'=>10, 'nama'=>'Kabupaten Ngawi                             '],
            ['id_provinsi'=>10, 'nama'=>'Kabupaten Pacitan                           '],
            ['id_provinsi'=>10, 'nama'=>'Kabupaten Pamekasan                         '],
            ['id_provinsi'=>10, 'nama'=>'Kabupaten Pasuruan                          '],
            ['id_provinsi'=>10, 'nama'=>'Kabupaten Ponorogo                          '],
            ['id_provinsi'=>10, 'nama'=>'Kabupaten Probolinggo                       '],
            ['id_provinsi'=>10, 'nama'=>'Kabupaten Sampang                           '],
            ['id_provinsi'=>10, 'nama'=>'Kabupaten Sidoarjo                          '],
            ['id_provinsi'=>10, 'nama'=>'Kabupaten Situbondo                         '],
            ['id_provinsi'=>10, 'nama'=>'Kabupaten Sumenep                           '],
            ['id_provinsi'=>10, 'nama'=>'Kabupaten Trenggalek                        '],
            ['id_provinsi'=>10, 'nama'=>'Kabupaten Tuban                             '],
            ['id_provinsi'=>10, 'nama'=>'Kabupaten Tulungagung                       '],
            ['id_provinsi'=>10, 'nama'=>'Kota Batu                                   '],
            ['id_provinsi'=>10, 'nama'=>'Kota Blitar                                 '],
            ['id_provinsi'=>10, 'nama'=>'Kota Kediri                                 '],
            ['id_provinsi'=>10, 'nama'=>'Kota Madiun                                 '],
            ['id_provinsi'=>10, 'nama'=>'Kota Malang                                 '],
            ['id_provinsi'=>10, 'nama'=>'Kota Mojokerto                              '],
            ['id_provinsi'=>10, 'nama'=>'Kota Pasuruan                               '],
            ['id_provinsi'=>10, 'nama'=>'Kota Probolinggo                            '],
            ['id_provinsi'=>10, 'nama'=>'Kota Surabaya                               '],
            ['id_provinsi'=>31, 'nama'=>'Kabupaten Bantul                            '],
            ['id_provinsi'=>31, 'nama'=>'Kabupaten Gunung Kidul                      '],
            ['id_provinsi'=>31, 'nama'=>'Kabupaten Kulon Progo                       '],
            ['id_provinsi'=>31, 'nama'=>'Kabupaten Sleman                            '],
            ['id_provinsi'=>31, 'nama'=>'Kota Yogyakarta                             '],
            ['id_provinsi'=>4, 'nama'=>'Kabupaten Badung                            '],
            ['id_provinsi'=>4, 'nama'=>'Kabupaten Bangli                            '],
            ['id_provinsi'=>4, 'nama'=>'Kabupaten Buleleng                          '],
            ['id_provinsi'=>4, 'nama'=>'Kabupaten Gianyar                           '],
            ['id_provinsi'=>4, 'nama'=>'Kabupaten Jembrana                          '],
            ['id_provinsi'=>4, 'nama'=>'Kabupaten Karangasem                        '],
            ['id_provinsi'=>4, 'nama'=>'Kabupaten Klungkung                         '],
            ['id_provinsi'=>4, 'nama'=>'Kabupaten Tabanan                           '],
            ['id_provinsi'=>4, 'nama'=>'Kota Denpasar                               '],
            ['id_provinsi'=>20, 'nama'=>'Kabupaten Bima                              '],
            ['id_provinsi'=>20, 'nama'=>'Kabupaten Dompu                             '],
            ['id_provinsi'=>20, 'nama'=>'Kabupaten Lombok Barat                      '],
            ['id_provinsi'=>20, 'nama'=>'Kabupaten Lombok Tengah                     '],
            ['id_provinsi'=>20, 'nama'=>'Kabupaten Lombok Timur                      '],
            ['id_provinsi'=>20, 'nama'=>'Kabupaten Lombok Utara                      '],
            ['id_provinsi'=>20, 'nama'=>'Kabupaten Sumbawa                           '],
            ['id_provinsi'=>20, 'nama'=>'Kabupaten Sumbawa Barat                     '],
            ['id_provinsi'=>20, 'nama'=>'Kota Bima                                   '],
            ['id_provinsi'=>20, 'nama'=>'Kota Mataram                                '],
            ['id_provinsi'=>21, 'nama'=>'Kabupaten Alor                              '],
            ['id_provinsi'=>21, 'nama'=>'Kabupaten Belu                              '],
            ['id_provinsi'=>21, 'nama'=>'Kabupaten Ende                              '],
            ['id_provinsi'=>21, 'nama'=>'Kabupaten Flores Timur                      '],
            ['id_provinsi'=>21, 'nama'=>'Kabupaten Kupang                            '],
            ['id_provinsi'=>21, 'nama'=>'Kabupaten Lembata                           '],
            ['id_provinsi'=>21, 'nama'=>'Kabupaten Manggarai                         '],
            ['id_provinsi'=>21, 'nama'=>'Kabupaten Manggarai Barat                   '],
            ['id_provinsi'=>21, 'nama'=>'Kabupaten Manggarai Timur                   '],
            ['id_provinsi'=>21, 'nama'=>'Kabupaten Ngada                             '],
            ['id_provinsi'=>21, 'nama'=>'Kabupaten Nagekeo                           '],
            ['id_provinsi'=>21, 'nama'=>'Kabupaten Rote Ndao                         '],
            ['id_provinsi'=>21, 'nama'=>'Kabupaten Sabu Raijua                       '],
            ['id_provinsi'=>21, 'nama'=>'Kabupaten Sikka                             '],
            ['id_provinsi'=>21, 'nama'=>'Kabupaten Sumba Barat                       '],
            ['id_provinsi'=>21, 'nama'=>'Kabupaten Sumba Barat Daya                  '],
            ['id_provinsi'=>21, 'nama'=>'Kabupaten Sumba Tengah                      '],
            ['id_provinsi'=>21, 'nama'=>'Kabupaten Sumba Timur                       '],
            ['id_provinsi'=>21, 'nama'=>'Kabupaten Timor Tengah Selatan              '],
            ['id_provinsi'=>21, 'nama'=>'Kabupaten Timor Tengah Utara                '],
            ['id_provinsi'=>21, 'nama'=>'Kota Kupang                                 '],
            ['id_provinsi'=>11, 'nama'=>'Kabupaten Bengkayang                        '],
            ['id_provinsi'=>11, 'nama'=>'Kabupaten Kapuas Hulu                       '],
            ['id_provinsi'=>11, 'nama'=>'Kabupaten Kayong Utara                      '],
            ['id_provinsi'=>11, 'nama'=>'Kabupaten Ketapang                          '],
            ['id_provinsi'=>11, 'nama'=>'Kabupaten Kubu Raya                         '],
            ['id_provinsi'=>11, 'nama'=>'Kabupaten Landak                            '],
            ['id_provinsi'=>11, 'nama'=>'Kabupaten Melawi                            '],
            ['id_provinsi'=>11, 'nama'=>'Kabupaten Pontianak                         '],
            ['id_provinsi'=>11, 'nama'=>'Kabupaten Sambas                            '],
            ['id_provinsi'=>11, 'nama'=>'Kabupaten Sanggau                           '],
            ['id_provinsi'=>11, 'nama'=>'Kabupaten Sekadau                           '],
            ['id_provinsi'=>11, 'nama'=>'Kabupaten Sintang                           '],
            ['id_provinsi'=>11, 'nama'=>'Kota Pontianak                              '],
            ['id_provinsi'=>11, 'nama'=>'Kota Singkawang                             '],
            ['id_provinsi'=>12, 'nama'=>'Kabupaten Balangan                          '],
            ['id_provinsi'=>12, 'nama'=>'Kabupaten Banjar                            '],
            ['id_provinsi'=>12, 'nama'=>'Kabupaten Barito Kuala                      '],
            ['id_provinsi'=>12, 'nama'=>'Kabupaten Hulu Sungai Selatan               '],
            ['id_provinsi'=>12, 'nama'=>'Kabupaten Hulu Sungai Tengah                '],
            ['id_provinsi'=>12, 'nama'=>'Kabupaten Hulu Sungai Utara                 '],
            ['id_provinsi'=>12, 'nama'=>'Kabupaten Kotabaru                          '],
            ['id_provinsi'=>12, 'nama'=>'Kabupaten Tabalong                          '],
            ['id_provinsi'=>12, 'nama'=>'Kabupaten Tanah Bumbu                       '],
            ['id_provinsi'=>12, 'nama'=>'Kabupaten Tanah Laut                        '],
            ['id_provinsi'=>12, 'nama'=>'Kabupaten Tapin                             '],
            ['id_provinsi'=>12, 'nama'=>'Kota Banjarbaru                             '],
            ['id_provinsi'=>12, 'nama'=>'Kota Banjarmasin                            '],
            ['id_provinsi'=>13, 'nama'=>'Kabupaten Barito Selatan                    '],
            ['id_provinsi'=>13, 'nama'=>'Kabupaten Barito Timur                      '],
            ['id_provinsi'=>13, 'nama'=>'Kabupaten Barito Utara                      '],
            ['id_provinsi'=>13, 'nama'=>'Kabupaten Gunung Mas                        '],
            ['id_provinsi'=>13, 'nama'=>'Kabupaten Kapuas                            '],
            ['id_provinsi'=>13, 'nama'=>'Kabupaten Katingan                          '],
            ['id_provinsi'=>13, 'nama'=>'Kabupaten Kotawaringin Barat                '],
            ['id_provinsi'=>13, 'nama'=>'Kabupaten Kotawaringin Timur                '],
            ['id_provinsi'=>13, 'nama'=>'Kabupaten Lamandau                          '],
            ['id_provinsi'=>13, 'nama'=>'Kabupaten Murung Raya                       '],
            ['id_provinsi'=>13, 'nama'=>'Kabupaten Pulang Pisau                      '],
            ['id_provinsi'=>13, 'nama'=>'Kabupaten Sukamara                          '],
            ['id_provinsi'=>13, 'nama'=>'Kabupaten Seruyan                           '],
            ['id_provinsi'=>13, 'nama'=>'Kota Palangka Raya                          '],
            ['id_provinsi'=>14, 'nama'=>'Kabupaten Berau                             '],
            ['id_provinsi'=>34, 'nama'=>'Kabupaten Bulungan                          '],
            ['id_provinsi'=>14, 'nama'=>'Kabupaten Kutai Barat                       '],
            ['id_provinsi'=>14, 'nama'=>'Kabupaten Kutai Kartanegara                 '],
            ['id_provinsi'=>14, 'nama'=>'Kabupaten Kutai Timur                       '],
            ['id_provinsi'=>34, 'nama'=>'Kabupaten Malinau                           '],
            ['id_provinsi'=>34, 'nama'=>'Kabupaten Nunukan                           '],
            ['id_provinsi'=>14, 'nama'=>'Kabupaten Paser                             '],
            ['id_provinsi'=>14, 'nama'=>'Kabupaten Penajam Paser Utara               '],
            ['id_provinsi'=>34, 'nama'=>'Kabupaten Tana Tidung                       '],
            ['id_provinsi'=>14, 'nama'=>'Kota Balikpapan                             '],
            ['id_provinsi'=>14, 'nama'=>'Kota Bontang                                '],
            ['id_provinsi'=>14, 'nama'=>'Kota Samarinda                              '],
            ['id_provinsi'=>34, 'nama'=>'Kota Tarakan                                '],
            ['id_provinsi'=>7, 'nama'=>'Kabupaten Boalemo                           '],
            ['id_provinsi'=>7, 'nama'=>'Kabupaten Bone Bolango                      '],
            ['id_provinsi'=>7, 'nama'=>'Kabupaten Gorontalo                         '],
            ['id_provinsi'=>7, 'nama'=>'Kabupaten Gorontalo Utara                   '],
            ['id_provinsi'=>7, 'nama'=>'Kabupaten Pohuwato                          '],
            ['id_provinsi'=>7, 'nama'=>'Kota Gorontalo                              '],
            ['id_provinsi'=>24, 'nama'=>'Kabupaten Bantaeng                          '],
            ['id_provinsi'=>24, 'nama'=>'Kabupaten Barru                             '],
            ['id_provinsi'=>24, 'nama'=>'Kabupaten Bone                              '],
            ['id_provinsi'=>24, 'nama'=>'Kabupaten Bulukumba                         '],
            ['id_provinsi'=>24, 'nama'=>'Kabupaten Enrekang                          '],
            ['id_provinsi'=>24, 'nama'=>'Kabupaten Gowa                              '],
            ['id_provinsi'=>24, 'nama'=>'Kabupaten Jeneponto                         '],
            ['id_provinsi'=>24, 'nama'=>'Kabupaten Kepulauan Selayar                 '],
            ['id_provinsi'=>24, 'nama'=>'Kabupaten Luwu                              '],
            ['id_provinsi'=>24, 'nama'=>'Kabupaten Luwu Timur                        '],
            ['id_provinsi'=>24, 'nama'=>'Kabupaten Luwu Utara                        '],
            ['id_provinsi'=>24, 'nama'=>'Kabupaten Maros                             '],
            ['id_provinsi'=>24, 'nama'=>'Kabupaten Pangkajene dan Kepulauan          '],
            ['id_provinsi'=>24, 'nama'=>'Kabupaten Pinrang                           '],
            ['id_provinsi'=>24, 'nama'=>'Kabupaten Sidenreng Rappang                 '],
            ['id_provinsi'=>24, 'nama'=>'Kabupaten Sinjai                            '],
            ['id_provinsi'=>24, 'nama'=>'Kabupaten Soppeng                           '],
            ['id_provinsi'=>24, 'nama'=>'Kabupaten Takalar                           '],
            ['id_provinsi'=>24, 'nama'=>'Kabupaten Tana Toraja                       '],
            ['id_provinsi'=>24, 'nama'=>'Kabupaten Toraja Utara                      '],
            ['id_provinsi'=>24, 'nama'=>'Kabupaten Wajo                              '],
            ['id_provinsi'=>24, 'nama'=>'Kota Makassar                               '],
            ['id_provinsi'=>24, 'nama'=>'Kota Palopo                                 '],
            ['id_provinsi'=>24, 'nama'=>'Kota Parepare                               '],
            ['id_provinsi'=>26, 'nama'=>'Kabupaten Bombana                           '],
            ['id_provinsi'=>26, 'nama'=>'Kabupaten Buton                             '],
            ['id_provinsi'=>26, 'nama'=>'Kabupaten Buton Utara                       '],
            ['id_provinsi'=>26, 'nama'=>'Kabupaten Kolaka                            '],
            ['id_provinsi'=>26, 'nama'=>'Kabupaten Kolaka Utara                      '],
            ['id_provinsi'=>26, 'nama'=>'Kabupaten Konawe                            '],
            ['id_provinsi'=>26, 'nama'=>'Kabupaten Konawe Selatan                    '],
            ['id_provinsi'=>26, 'nama'=>'Kabupaten Konawe Utara                      '],
            ['id_provinsi'=>26, 'nama'=>'Kabupaten Muna                              '],
            ['id_provinsi'=>26, 'nama'=>'Kabupaten Wakatobi                          '],
            ['id_provinsi'=>26, 'nama'=>'Kota Bau-Bau                                '],
            ['id_provinsi'=>26, 'nama'=>'Kota Kendari                                '],
            ['id_provinsi'=>25, 'nama'=>'Kabupaten Banggai                           '],
            ['id_provinsi'=>25, 'nama'=>'Kabupaten Banggai Kepulauan                 '],
            ['id_provinsi'=>25, 'nama'=>'Kabupaten Buol                              '],
            ['id_provinsi'=>25, 'nama'=>'Kabupaten Donggala                          '],
            ['id_provinsi'=>25, 'nama'=>'Kabupaten Morowali                          '],
            ['id_provinsi'=>25, 'nama'=>'Kabupaten Parigi Moutong                    '],
            ['id_provinsi'=>25, 'nama'=>'Kabupaten Poso                              '],
            ['id_provinsi'=>25, 'nama'=>'Kabupaten Tojo Una-Una                      '],
            ['id_provinsi'=>25, 'nama'=>'Kabupaten Toli-Toli                         '],
            ['id_provinsi'=>25, 'nama'=>'Kabupaten Sigi                              '],
            ['id_provinsi'=>25, 'nama'=>'Kota Palu                                   '],
            ['id_provinsi'=>27, 'nama'=>'Kabupaten Bolaang Mongondow                 '],
            ['id_provinsi'=>27, 'nama'=>'Kabupaten Bolaang Mongondow Selatan         '],
            ['id_provinsi'=>27, 'nama'=>'Kabupaten Bolaang Mongondow Timur           '],
            ['id_provinsi'=>27, 'nama'=>'Kabupaten Bolaang Mongondow Utara           '],
            ['id_provinsi'=>27, 'nama'=>'Kabupaten Kepulauan Sangihe                 '],
            ['id_provinsi'=>27, 'nama'=>'Kabupaten Kepulauan Siau Tagulandang Biaro  '],
            ['id_provinsi'=>27, 'nama'=>'Kabupaten Kepulauan Talaud                  '],
            ['id_provinsi'=>27, 'nama'=>'Kabupaten Minahasa                          '],
            ['id_provinsi'=>27, 'nama'=>'Kabupaten Minahasa Selatan                  '],
            ['id_provinsi'=>27, 'nama'=>'Kabupaten Minahasa Tenggara                 '],
            ['id_provinsi'=>27, 'nama'=>'Kabupaten Minahasa Utara                    '],
            ['id_provinsi'=>27, 'nama'=>'Kota Bitung                                 '],
            ['id_provinsi'=>27, 'nama'=>'Kota Kotamobagu                             '],
            ['id_provinsi'=>27, 'nama'=>'Kota Manado                                 '],
            ['id_provinsi'=>27, 'nama'=>'Kota Tomohon                                '],
            ['id_provinsi'=>32, 'nama'=>'Kabupaten Majene                            '],
            ['id_provinsi'=>32, 'nama'=>'Kabupaten Mamasa                            '],
            ['id_provinsi'=>32, 'nama'=>'Kabupaten Mamuju                            '],
            ['id_provinsi'=>32, 'nama'=>'Kabupaten Mamuju Utara                      '],
            ['id_provinsi'=>32, 'nama'=>'Kabupaten Polewali Mandar                   '],
            ['id_provinsi'=>17, 'nama'=>'Kabupaten Buru                              '],
            ['id_provinsi'=>17, 'nama'=>'Kabupaten Buru Selatan                      '],
            ['id_provinsi'=>17, 'nama'=>'Kabupaten Kepulauan Aru                     '],
            ['id_provinsi'=>17, 'nama'=>'Kabupaten Maluku Barat Daya                 '],
            ['id_provinsi'=>17, 'nama'=>'Kabupaten Maluku Tengah                     '],
            ['id_provinsi'=>17, 'nama'=>'Kabupaten Maluku Tenggara                   '],
            ['id_provinsi'=>17, 'nama'=>'Kabupaten Maluku Tenggara Barat             '],
            ['id_provinsi'=>17, 'nama'=>'Kabupaten Seram Bagian Barat                '],
            ['id_provinsi'=>17, 'nama'=>'Kabupaten Seram Bagian Timur                '],
            ['id_provinsi'=>17, 'nama'=>'Kota Ambon                                  '],
            ['id_provinsi'=>17, 'nama'=>'Kota Tual                                   '],
            ['id_provinsi'=>18, 'nama'=>'Kabupaten Halmahera Barat                   '],
            ['id_provinsi'=>18, 'nama'=>'Kabupaten Halmahera Tengah                  '],
            ['id_provinsi'=>18, 'nama'=>'Kabupaten Halmahera Utara                   '],
            ['id_provinsi'=>18, 'nama'=>'Kabupaten Halmahera Selatan                 '],
            ['id_provinsi'=>18, 'nama'=>'Kabupaten Kepulauan Sula                    '],
            ['id_provinsi'=>18, 'nama'=>'Kabupaten Halmahera Timur                   '],
            ['id_provinsi'=>18, 'nama'=>'Kabupaten Pulau Morotai                     '],
            ['id_provinsi'=>18, 'nama'=>'Kota Ternate                                '],
            ['id_provinsi'=>18, 'nama'=>'Kota Tidore Kepulauan                       '],
            ['id_provinsi'=>22, 'nama'=>'Kabupaten Asmat                             '],
            ['id_provinsi'=>22, 'nama'=>'Kabupaten Biak Numfor                       '],
            ['id_provinsi'=>22, 'nama'=>'Kabupaten Boven Digoel                      '],
            ['id_provinsi'=>22, 'nama'=>'Kabupaten Deiyai                            '],
            ['id_provinsi'=>22, 'nama'=>'Kabupaten Dogiyai                           '],
            ['id_provinsi'=>22, 'nama'=>'Kabupaten Intan Jaya                        '],
            ['id_provinsi'=>22, 'nama'=>'Kabupaten Jayapura                          '],
            ['id_provinsi'=>22, 'nama'=>'Kabupaten Jayawijaya                        '],
            ['id_provinsi'=>22, 'nama'=>'Kabupaten Keerom                            '],
            ['id_provinsi'=>22, 'nama'=>'Kabupaten Kepulauan Yapen                   '],
            ['id_provinsi'=>22, 'nama'=>'Kabupaten Lanny Jaya                        '],
            ['id_provinsi'=>22, 'nama'=>'Kabupaten Mamberamo Raya                    '],
            ['id_provinsi'=>22, 'nama'=>'Kabupaten Mamberamo Tengah                  '],
            ['id_provinsi'=>22, 'nama'=>'Kabupaten Mappi                             '],
            ['id_provinsi'=>22, 'nama'=>'Kabupaten Merauke                           '],
            ['id_provinsi'=>22, 'nama'=>'Kabupaten Mimika                            '],
            ['id_provinsi'=>22, 'nama'=>'Kabupaten Nabire                            '],
            ['id_provinsi'=>22, 'nama'=>'Kabupaten Nduga                             '],
            ['id_provinsi'=>22, 'nama'=>'Kabupaten Paniai                            '],
            ['id_provinsi'=>22, 'nama'=>'Kabupaten Pegunungan Bintang                '],
            ['id_provinsi'=>22, 'nama'=>'Kabupaten Puncak                            '],
            ['id_provinsi'=>22, 'nama'=>'Kabupaten Puncak Jaya                       '],
            ['id_provinsi'=>22, 'nama'=>'Kabupaten Sarmi                             '],
            ['id_provinsi'=>22, 'nama'=>'Kabupaten Supiori                           '],
            ['id_provinsi'=>22, 'nama'=>'Kabupaten Tolikara                          '],
            ['id_provinsi'=>22, 'nama'=>'Kabupaten Waropen                           '],
            ['id_provinsi'=>22, 'nama'=>'Kabupaten Yahukimo                          '],
            ['id_provinsi'=>22, 'nama'=>'Kabupaten Yalimo                            '],
            ['id_provinsi'=>22, 'nama'=>'Kota Jayapura                               '],
            ['id_provinsi'=>19, 'nama'=>'Kabupaten Fakfak                            '],
            ['id_provinsi'=>19, 'nama'=>'Kabupaten Kaimana                           '],
            ['id_provinsi'=>19, 'nama'=>'Kabupaten Manokwari                         '],
            ['id_provinsi'=>19, 'nama'=>'Kabupaten Maybrat                           '],
            ['id_provinsi'=>19, 'nama'=>'Kabupaten Raja Ampat                        '],
            ['id_provinsi'=>19, 'nama'=>'Kabupaten Sorong                            '],
            ['id_provinsi'=>19, 'nama'=>'Kabupaten Sorong Selatan                    '],
            ['id_provinsi'=>19, 'nama'=>'Kabupaten Tambrauw                          '],
            ['id_provinsi'=>19, 'nama'=>'Kabupaten Teluk Bintuni                     '],
            ['id_provinsi'=>19, 'nama'=>'Kabupaten Teluk Wondama                     '],
            ['id_provinsi'=>19, 'nama'=>'Kota Sorong                                 '],
            ['id_provinsi'=>22, 'nama'=>'Kabupaten Sikka                             '],
            ['id_provinsi'=>30, 'nama'=>'Kabupaten Banyuasin                         '],
            ['id_provinsi'=>30, 'nama'=>'Kabupaten Empat Lawang                      '],
            ['id_provinsi'=>30, 'nama'=>'Kabupaten Lahat                             '],
            ['id_provinsi'=>30, 'nama'=>'Kabupaten Muara Enim                        '],
            ['id_provinsi'=>30, 'nama'=>'Kabupaten Musi Banyuasin                    '],
            ['id_provinsi'=>30, 'nama'=>'Kabupaten Musi Rawas                        '],
            ['id_provinsi'=>30, 'nama'=>'Kabupaten Ogan Ilir                         '],
            ['id_provinsi'=>30, 'nama'=>'Kabupaten Ogan Komering Ilir                '],
            ['id_provinsi'=>30, 'nama'=>'Kabupaten Ogan Komering Ulu                 '],
            ['id_provinsi'=>30, 'nama'=>'Kabupaten Penukal Abab Lematang Ilir        '],
            ['id_provinsi'=>30, 'nama'=>'Kota Lubuk Linggau                          '],
            ['id_provinsi'=>30, 'nama'=>'Kota Pagar Alam                             '],
            ['id_provinsi'=>30, 'nama'=>'Kota Palembang                              '],
            ['id_provinsi'=>30, 'nama'=>'Kota Prabumulih                             '],
            ['id_provinsi'=>30, 'nama'=>'Kabupaten Asahan                            '],
            ['id_provinsi'=>30, 'nama'=>'Kabupaten Batubara                          '],
            ['id_provinsi'=>30, 'nama'=>'Kabupaten Dairi                             '],
            ['id_provinsi'=>30, 'nama'=>'Kabupaten Deli Serdang                      '],
            ['id_provinsi'=>30, 'nama'=>'Kabupaten Humbang Hasundutan                '],
            ['id_provinsi'=>30, 'nama'=>'Kabupaten Karo                              '],
            ['id_provinsi'=>30, 'nama'=>'Kabupaten Labuhanbatu                       '],
            ['id_provinsi'=>30, 'nama'=>'Kabupaten Labuhanbatu Selatan               '],
            ['id_provinsi'=>30, 'nama'=>'Kabupaten Labuhanbatu Utara                 '],
            ['id_provinsi'=>30, 'nama'=>'Kabupaten Langkat                           '],
            ['id_provinsi'=>30, 'nama'=>'Kabupaten Mandailing Natal                  '],
            ['id_provinsi'=>30, 'nama'=>'Kabupaten Nias                              '],
            ['id_provinsi'=>30, 'nama'=>'Kabupaten Nias Barat                        '],
            ['id_provinsi'=>30, 'nama'=>'Kabupaten Nias Selatan                      '],
            ['id_provinsi'=>30, 'nama'=>'Kabupaten Nias Utara                        '],
            ['id_provinsi'=>30, 'nama'=>'Kabupaten Padang Lawas                      '],
            ['id_provinsi'=>30, 'nama'=>'Kabupaten Padang Lawas Utara                '],
            ['id_provinsi'=>30, 'nama'=>'Kabupaten Pakpak Bharat                     '],
            ['id_provinsi'=>30, 'nama'=>'Kabupaten Samosir                           '],
            ['id_provinsi'=>30, 'nama'=>'Kabupaten Serdang Bedagai                   '],
            ['id_provinsi'=>30, 'nama'=>'Kabupaten Simalungun                        '],
            ['id_provinsi'=>30, 'nama'=>'Kabupaten Tapanuli Selatan                  '],
            ['id_provinsi'=>30, 'nama'=>'Kabupaten Tapanuli Tengah                   '],
            ['id_provinsi'=>30, 'nama'=>'Kabupaten Tapanuli Utara                    '],
            ['id_provinsi'=>30, 'nama'=>'Kabupaten Toba Samosir                      '],
            ['id_provinsi'=>30, 'nama'=>'Kota Binjai                                 '],
            ['id_provinsi'=>30, 'nama'=>'Kota Gunungsitoli                           '],
            ['id_provinsi'=>30, 'nama'=>'Kota Medan                                  '],
            ['id_provinsi'=>30, 'nama'=>'Kota Padangsidempuan                        '],
            ['id_provinsi'=>30, 'nama'=>'Kota Pematangsiantar                        '],
            ['id_provinsi'=>30, 'nama'=>'Kota Sibolga                                '],
            ['id_provinsi'=>30, 'nama'=>'Kota Tanjungbalai                           '],
            ['id_provinsi'=>30, 'nama'=>'Kota Tebing Tinggi']
    ];

    public function up()
    {
        Schema::create('kota', function (Blueprint $table) {
          $table->bigincrements('id');
          $table->biginteger('id_provinsi')->unsigned();
          $table->string('nama');
        });

        DB::table('kota')->insert(self::$kota);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('kota');
    }
}
